---
title: "Consumption and Growth Quizzes"
output: html_notebook
---

```{r}
# refresh environment
rm(list = ls())
```

## Consumption Quiz

```{r}
printVal <- function(c1 = 0, c2 = 0) {
  c1 <- round(c1, 2)
  c2 <- round(c2, 2)
  print(paste0("Present consumption (C1) is: ", c1))
  print(paste0("Future consumption (C2) is: ", c2))
}
```

### Problem Parameters

```{r}
# Period One
y1 <- 200
w1 <- 100

# Period Two
y2 <- 250
w2 <- 75

# Real interest rate
r <- 0.03
```

### Leonard

```{r}
# Consumes all in current period

# c2 = 0
# c1 = (y1 + w1) + (y2 + w2) / (1 + r)
c1 <- (y1 + w1) + (y2 + w2) / (1 + r)
c2 <- 0
printVal(c1, c2)
```

### Penny

```{r}
# Consumes all in future period

# c1 = 0
# c2 / (1 + r) = (y1 + w1) + (y2 + w2) / (1 + r)
# c2 = (y1 + w1) * (1 + r) + (y2 + w2)
c1 <- 0
c2 <- ((y1 + w1) * (1 + r)) + (y2 + w2)
printVal(c1, c2)
```

### Sheldon

```{r}
# Perfect consumption smoothing

# c1 = c2
# c1 + c1 / (1 + r) = (y1 + w1) + (y2 + w2) / (1 + r)
# c1 * (1 + r) + c1 = ((y1 + w1) * (1 + r)) + (y2 + w2)
# c1 * (2 + r) = ((y1 + w1) * (1 + r)) + (y2 + w2)
# c1 = (((y1 + w1) * (1 + r)) + (y2 + w2)) / (2 + r)
c1 <- (((y1 + w1) * (1 + r)) + (y2 + w2)) / (2 + r)
c2 <- c1
printVal(c1, c2)
```

### Amy

```{r}
# Consume twice as much in future (saver)

# c1 = 1/2 * c2
# c1 + (2 * c1) / (1 + r) = (y1 + w1) + (y2 + w2) / (1 + r)
# c1 * (1 + r) + 2 * c1 = ((y1 + w1) * (1 + r)) + (y2 + w2)
# c1 * (3 + r) = ((y1 + w1) * (1 + r)) + (y2 + w2)
# c1 = (((y1 + w1) * (1 + r)) + (y2 + w2)) / (3 + r)
c1 <- (((y1 + w1) * (1 + r)) + (y2 + w2)) / (3 + r)
c2 <- 2 * c1
printVal(c1, c2)
```

### Howard

```{r}
# Does not want to borrow or save - NB/NL

# c1 = y1 + w1
# c2 = y2 + w2
c1 <- y1 + w1
c2 <- y2 + w2
printVal(c1, c2)
```

### Bernadette

```{r}
# Consume twice as much now

# c1 = 2 * c2
# c1 + (1/2 * c1) / (1 + r) = (y1 + w1) + (y2 + w2) / (1 + r)
# c1 * (1 + r) + (1 / 2) * c1 = ((y1 + w1) * (1 + r)) + (y2 + w2)
# c1 * (1.5 + r) = ((y1 + w1) * (1 + r)) + (y2 + w2)
# c1 = (((y1 + w1) * (1 + r)) + (y2 + w2)) / (1.5 + r)
c1 <- (((y1 + w1) * (1 + r)) + (y2 + w2)) / (1.5 + r)
c2 <- 0.5 * c1
printVal(c1, c2)
```


## Growth Quiz

```{r}
printLetter <- function(val = 0, letter) {
  print(paste0(letter," = ", val))
}
```

### Parameters

```{r}
# Growth rate
n <- 0.02

# per worker production
y <- function(k = 0) {
  return(6 * (k ^ 0.5))
}

# Depreciation rate
d <- 0.13
```

### Part a

```{r}
# households consume 90% - save 10%
s <- 0.10

# steady state condition
# s * y = (n + d) * k
# s * 6k^0.5 = (n + d) * k
# s = (n + d) * k ^ 0.5 / 6
# 6 * s / (n + d) = k ^ 0.5
# k = ((6 * s) / (n + d)) ^ 2
k <- ((6 * s) / (n + d)) ^ 2
printLetter(k, "A")

# y is per worker production function
yStar <- y(k)
printLetter(yStar, "B")

# consumption is production - savings (or investment)
# c = y - y * s
c <- yStar - (yStar * s)
printLetter(c, "C")
```

### Part b

```{r}
# we want to double output
# to do so we need to increase input to capital
# 6 * k ^ 0.5 = 48
# k ^ 0.5 = 8
# k = 8 ^ 2
k2 <- (yStar / 3) ^ 2
printLetter(k2, "D")
```

### Part c

```{r}
# what s do we need to achieve k of 64
# s = (n + d) * k / y
s2 <- ((n + d) * k2) / (2 * yStar)
printLetter(s2, "E")
```




