---
title: "Exam 2 Main Concepts"
output:
  pdf_document: 
    toc: true
    toc_depth: 2
    number_sections: true
  html_notebook: default
---

```{r include = FALSE}
# refresh environment
rm(list = ls())

library(mdsr) # utility package for tidyverse
```


# Lesson 4

## Job Finding Rate

Probability of find a job
\[
f = \frac{H(U, V)}{U}
\]
\[
f = \gamma \sqrt{\theta}
\]

$\frac{1}{f}$ - average length of unemployment

## Vacancy Filling Rate

Probability of filling a vacancy
\[
q = \frac{H(U, V)}{V}
\]
\[
q = \gamma (\theta)^{-1/2}
\]

$\frac{1}{q}$ - average length of vacancy (time to fill)

## Steady-State Unemployment

Natural rate of unemployment when $f * U = s * E$:
\[
u* = \frac{s}{(s + f(\theta))}
\]

This is known as the Beveridge curve.

## Vacancy-Supply Curve

\[
\theta(w) = (\frac{\gamma * (y - w)}{s * k})^2
\]

## Wage-Setting Curve

Will be given as $w(\theta)$

# Lesson 5

## IBL

Find equation of consumption values from preferences and plug into $PVLC = PVLR$

\[
C_1 + \frac{C_2}{(1 + r)} = (Y_1 + W_1) + \frac{(Y_2 + W_2)}{(1 + r)}
\]

* Y-intercept = Only Future consumption (C~2~)
* X-intercept = Only Current consumption (C~1~)
* intserction of IBL and y = x is C~1~ = C~2~ (Consumption Smoothing)
* No-Lending/No-Borrowing Point
    + C~1~ = Y~1~ + W~1~
    + C~2~ = Y~2~ + W~2~
* Slope = -(1 + r)
    + r = real interest rate

# Lesson 6

## UC = MPK

Firms will choose a level of capital (K) that maximizes profit by reaching the
condition $MB = MC$

MB = Expected marginal product of capital (MPK^e^)

MC = User-cost of capital (UC)

$\pi_{max}$ when UC = MPK^e^

User Cost depends on:

* Real Price of capital (P~k~)
* The depreciation rate ($\delta$)
* The real interest rate (r)
* The business tax on revenue ($\tau$)
* Investment Tax Credit (ITC)

\[
UC = \frac{(r + \delta)(1 - ITC)P_k}{(1 - \tau)}
\]

## Savings and Investment


I~t~ = Gross investment in year t
K~t~ = capital stock at beginning of year t
K~t+1~ = capital stock at beginning of year t + 1

* Net investment = $\Delta K$ during year t
    + $K_{t+1} - K_t$
* Net investment = gross investment - depreciation

### Goods Market Equlibrium

* We are in a closed economy so NX = 0
* Savings = Investment

\[
I = Y - C - G
\]

### Savings Function

\[
S = Y - C - G
\]

* Y +
* Y~2~ -
* W~1~ -
* W~2~ -
* T +
* Autonomous Consumption -
* Consumer confidence -
* G -

### Investment Function

\[
I = K^* - K_t + \delta K_t
\]

* A +
* AS +
* $\tau$ -
* $\delta$ -
* P~k~ -
* ITC +

# Lesson 7

## Notation

* L~t~ - Number of workers
* n - growth rate of work force
    + population growth rate
* K~t~ - capital stock
* $\delta$ - depreciation rate
* Y~t~ - output (GDP)
* C~t~ - consumption
* I~t~ - gross investment
    + $C_t = Y_t - I_t$
* $y_t = \frac{Y_t}{L_t}$ - ouput per worker
* $c_t = \frac{C_t}{L_t}$ - consumption per worker
* $k_t = \frac{K_t}{L_t}$ - capital per worker (capital-labor ratio)
* $i_t = \frac{I_t}{L_t}$ - investment per worker


## Steady-State

\[
i = (n + \delta)k
\]

\[
y_t = Af(k_t)
\]

\[
c = Af(k) - (n + \delta)k
\]
STEADY STATE CONDITION
\[
sf(k) = (n + \delta)k
\]

There are three main factors that change the solow model

1. Changes in TFP (A) change $sf(k)$
2. Cahnges in savings rate (s) change $sf(k)$
3. Changes in the population growth rate (n) change $(n + \delta)k$








